services:
  talentcheck-api:
    build: .
    restart: always
    env_file: .env
    network_mode: host
    labels:
      - traefik.enable=true
      - traefik.http.routers.talentcheck.rule=Host(`tc.srv867871.hstgr.cloud`)
      - traefik.http.routers.talentcheck.tls=true
      - traefik.http.routers.talentcheck.entrypoints=web,websecure
      - traefik.http.routers.talentcheck.tls.certresolver=mytlschallenge
      - traefik.http.services.talentcheck.loadbalancer.server.port=8001
